### ISSUE TITLE
How to force enable "toggle thumbnails" in responsive ?

### ISSUE THREAD

**Issue by s4miii** [LCweb-ita/LC-Lightbox-LITE#10]
Happy new year and thank you so much because of your great job!

is there any way to force `toggle thumbnails` in responsive views ?
I test it on my old iPhone 5s, and even I set `thumbs_nav` to `true`
in desktop view it's ok but in mobile view you have to enable it manually 
thanks again

**Comment by LCweb-ita** [comment]
Hello,
please check the "tn_hidden" option

https://lcweb.it/lc-lightbox/documentation?section=opts
