### ISSUE TITLE
Multiple LightBox in same web page

### ISSUE THREAD

**Issue by JArma19** [LCweb-ita/LC-Lightbox-LITE#7]
Hi, I'm trying to implement multiple lightboxes in the same page, with no success. 
The point is that all images in the page fall into a unique lightbox (i.e. Let's say I want two groups of 6 images each, when I click on one I should see just 6 images, not 12 as actually happens).
My problem is that I don't know how to manage "gallery_hook" option. Thanks for help

**Comment by stefantalpalaru** [comment]
> My problem is that I don't know how to manage "gallery_hook" option.

Say you have:

```html
<a href="{{ img.src }}" class="imglink" data-gallery-id="{{ album.id }}"><img src="{{ img.thumb_src }}"/></a>
```

This is how you have one gallery per album ID:

```js
lc_lightbox('a.imglink', {
    gallery_hook: 'data-gallery-id'
});
```

**Comment by LCweb-ita** [comment]
Thanks @stefantalpalaru, I totally missed the issue thread!
